spring:
  datasource:
    url: jdbc:h2:mem:test
  main:
    allow-circular-references: true
  sql:
    init: always
  h2:
    console:
      path: /h2-console
      settings:
        web-allow-others: true
