spring:
  datasource:
    url: jdbc:h2:file:~/libraryDb
  main:
    allow-circular-references: true
  flyway:
    locations:
      - classpath:db/migration
      - classpath:db/seed
  h2:
    console:
      path: /h2-console
      settings:
        web-allow-others: true
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
